Models/ErrorViewModel.cs
using System;

namespace EFCore.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Funcionario.cs
namespace EFCore.Models
{
    public class Funcionario
    {
        public int Id {get; set;}
        public string Nome {get; set;}
        public float Salario {get; set;}
        public string Cpf { get; set; }
    }
}

Controllers/FuncionarioController.cs
using System;
using System.Linq;
using EFCore.Database;
using EFCore.Models;
using Microsoft.AspNetCore.Mvc;

namespace EFCore.Controllers
{
    public class FuncionarioController : Controller
    {
        private readonly ApplicationDBContext _database;

        public FuncionarioController(ApplicationDBContext database)
        {
            this._database = database;
        }

        [HttpGet]
        public IActionResult Index(){
            var funcionarios = _database.Funcionarios.ToList();
            return View(funcionarios);
        }

        [HttpGet]
        public IActionResult Cadastrar(){
            return View();
        }
                
        [HttpGet]
        public IActionResult Editar(int id){
            var funcionario = _database.Funcionarios.First(func => func.Id == id);
            return View("Cadastrar", funcionario);
        }

        [HttpGet]
        public IActionResult Deletar(int id){
            var funcionario = _database.Funcionarios.First(func => func.Id == id);
            _database.Funcionarios.Remove(funcionario);
            _database.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Salvar(Funcionario modelo){
            if(modelo.Id == 0){
                _database.Funcionarios.Add(modelo);
            }
            else{
                //Este objeto já está na memoria do entity framework e por isso não precisa de método update
                //simplesmente modificar o objeto já faz alterar
                var funcionario = _database.Funcionarios.First(func => func.Id == modelo.Id);
                funcionario.Nome = modelo.Nome;
                funcionario.Cpf = modelo.Cpf;
                funcionario.Salario = modelo.Salario;
            }
            _database.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using EFCore.Models;

namespace EFCore.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Funcionario/Cadastrar.cshtml
@model EFCore.Models.Funcionario

<h2>Cadastro de Funcionários</h2>

<form class="form-horizontal" asp-controller="Funcionario" asp-action="Salvar" method="POST">
    <input type="hidden" asp-for="Id">
    <input type="text" class="form-control" asp-for="Nome" placeholder="Nome">
    <input type="number" class="form-control" asp-for="Salario" placeholder="Salário">
    <input type="text" class="form-control" asp-for="Cpf" placeholder="CPF">
    <button class="btn btn-success">Cadastrar</button>
</form>

Views/Funcionario/Index.cshtml
@model IEnumerable<EFCore.Models.Funcionario>

<h2>Todos os funcionários</h2>

<a href="/Funcionario/Cadastrar" class="btn btn-success">Novo Funcionário</a>
<hr>

@foreach (var item in Model)
{
    <p>CPF: @item.Cpf</p>
    <p>Nome: @item.Nome</p>
    <p>Salário: @item.Salario</p>
    <a href="/Funcionario/Editar/@item.Id" class="btn btn-success">Editar</a>
    <a href="/Funcionario/Deletar/@item.Id" class="btn btn-danger">Deletar</a>
    <hr>
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EFCore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EFCore</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - EFCore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>